--TODO: create separate sequences per table
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE "USER" (
    ID    BIGINT PRIMARY KEY,
    NAME  VARCHAR(255)        NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE PRODUCT (
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(255)        NOT NULL,
    NORM_NAME VARCHAR(255) UNIQUE NOT NULL,
    VERSION   INT                 NOT NULL CHECK ( VERSION >= 0 ),
    STOCK     INT                 NOT NULL CHECK ( STOCK >= 0 )
);

CREATE TABLE "ORDER" (
    ID      BIGINT PRIMARY KEY,
    USER_ID BIGINT       NOT NULL REFERENCES "USER"(ID) ON DELETE CASCADE,
    STATE   VARCHAR(255) NOT NULL CHECK ( STATE IN ('Creating', 'Finished')),
    DATE    TIMESTAMP
);

CREATE TABLE ORDER_PRODUCT (
    ORDER_ID   BIGINT NOT NULL REFERENCES "ORDER"(ID) ON DELETE CASCADE,
    PRODUCT_ID BIGINT NOT NULL REFERENCES PRODUCT(ID) ON DELETE CASCADE,
    QUANTITY   INT    NOT NULL CHECK ( QUANTITY >= 0 ),
    IDX        INT CHECK ( IDX >= 0 ),
    PRIMARY KEY (ORDER_ID, PRODUCT_ID)
);